# -*- coding: utf-8 -*-
"""Uso de pandas, numpy y matlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWg0a74IFhTX2DTqpHqNxUTo78juJHNx

**IMPORTACIONES**
"""

import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt;

"""**CARGA DE DATOS**"""

data_frame = pd.read_csv("Food_Preference.csv")
data_frame.head()

"""**TAMAÑO DEL DATASET**"""

data_frame.shape

"""**REVISION DE DATOS**"""

data_frame.dtypes

"""**TRATAMIENTO DE DATOS NULOS**"""

for feature in data_frame.columns:
    print('Total de valores nulos de', feature, '=', data_frame[feature].isna().sum())

"""**TECNICAS DE TRATAMIENTO DE VALORES NULOS Eliminar las observaciones (opción simple)**"""

data_frame = data_frame.dropna()
data_frame.shape

"""**EXPLORACION DE VALORES**

algunas estadisticas
"""

data_frame.describe()

"""La función anterior obtiene las estadísticas de una sola columna (en este caso hay 8), aparece solo
esa porque es la única columna numérica.
La interpretación:
1. Hay 284 valores en la columna
2. El promedio corresponde a 30.65
3. La desviación estándar es de 11.24, lo que quiere decir, la edad de las observaciones varía
dentro del intervalo [19.41, 41.89] [mean - std; mean + std]
4. Valor mínimo de la columna es 8
5. El 25% de las observaciones es menor a 24
6. El 50% de las observaciones es menor a 28
7. El 75% de las observaciones es menor a 37
8. El valor máximo de la columna es 80

**UNA ALTERNATIVA A LO ANTERIOR**
"""

print('Mínimo:',data_frame['Age'].min())
print('Máximo:',data_frame['Age'].max())
print('Promedio:',data_frame['Age'].mean())
print('STD:',data_frame['Age'].std())
print(data_frame.Age.quantile([.25, .5, .75]))
print('*******')
print('Mínimo:',min(data_frame['Age']))
print('Máximo:',max(data_frame['Age']))

data_frame.describe(include="all")

"""Considerando solo las columnas de tipo object"""

data_frame.describe(include=[object])

"""**AGRUPACIONES DE DATOS**"""

# Obtener total de pedidos considerando tipo de comida y género
data_frame.groupby('Gender')['Food'].value_counts()

# Obtener total de alternativas de postre por género
data_frame.groupby('Gender')['Dessert'].value_counts()

# Para comprobar los resultados anteriores
data_frame.groupby(data_frame.Gender).count()

# ¿Quiénes piden más postres, los hombres o las mujeres?
data_frame[data_frame.Dessert == 'Yes'].groupby('Gender')['Dessert'].count()

"""**GRAFICOS**"""

# Visualizamos de forma rápida las características de entrada, eliminando las columnas que no interesan
data_frame.drop(['Timestamp', 'Participant_ID'], axis=1).hist()
plt.show()
# Nuevamente, solo considera las columnas que son numéricas. La pregunta válida acá es, ¿cómo se
# puede graficar por ejemplo, la columna Food?
# La respuesta es variada a la pregunta, sin embargo, una alternativa es la que se indica a continuación:

def getGraficoBarras(label_x, label_y, title, feature):
    x_values = data_frame[feature].unique()
    y_values = data_frame[feature].value_counts().tolist()
    plt.bar(x_values, y_values)
    plt.title(title)
    plt.xlabel(label_x)
    plt.ylabel(label_y)
    plt.show()
getGraficoBarras('Tipos de comida', 'Nro.Obsevaciones', "Total de observaciones por tipo de comida", 'Food')

tipos = data_frame['Food'].unique()
total = data_frame['Food'].value_counts().tolist()
explode = [0.4 if total[0] == max(total) else 0, 0.4 if total[1] == max(total) else 0] # Destacar algunos
plt.pie(total, labels=tipos, explode=explode, autopct='%1.1f%%', shadow=True, startangle=90)
plt.title('Distribución de tipos de comida')
plt.show()

# Respondiendo, gráficamente a: ¿Quiénes piden más postres, los hombres o las mujeres?
df_pie = pd.DataFrame(data_frame[data_frame.Dessert == 'Yes'].groupby('Gender')['Dessert'].count())
colores = ["#EE6055","#60D394"]
plt.pie(np.array(df_pie).ravel(), labels=[df_pie.index[0],df_pie.index[1]],
autopct='%1.1f%%', shadow=True, startangle=90, colors = colores)
plt.title('Distribución por género de solicitud de postres')
plt.show()

"""**MANEJANDO LA CARTA DE COLORES**"""

from matplotlib import cm
from matplotlib import colors
df_pie = pd.DataFrame(data_frame[data_frame.Dessert == 'Yes'].groupby('Gender')['Dessert'].count())
normdata = colors.Normalize(min(df_pie.Dessert), max(df_pie.Dessert))
colormap = cm.get_cmap("Blues")
colores =colormap(normdata(np.array(df_pie).ravel()))
plt.pie(np.array(df_pie).ravel(), labels=[df_pie.index[0],df_pie.index[1]],
autopct='%1.1f%%', shadow=True, startangle=90, colors = colores)
plt.title('Distribución por género de solicitud de postres')
plt.show()

# Gráfico de densidad de edades
x_values = data_frame.Age.unique()
y_values = data_frame.Age.value_counts().tolist()
plt.scatter(x_values, y_values, marker='o');
#plt.plot(x_values, y_values)
plt.title('Densidad de edades')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.show()
11