# -*- coding: utf-8 -*-
"""MineriaDeDatos1.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsPl-PMk8LREBZAYDXgrqzfxzMPWX-rV
"""

#Comentarios Hola mundo
print("Hola mundo\n")

"""IMPORTS"""

import numpy as np
import pandas as pd

#===================================
#ARRAY UNIDIMENSIONAL
#===================================
array_uni = np.array([1,2,3,4,5])
print("ARRAY UNIDIMENSIONAL")
print(array_uni)
#==================================
#ARRAY BIDIMENSIONAL
#===================================
array_bid = np.array([[1,3,5],[2,4,6]])
print("ARRAY BIDIMENSIONAL")
print(array_bid, "\n")
#==================================
#ARRAY TRIDIMENSIONAL 2x2x30
#===================================
array_tri = np.array([
    #Fila 0 y 2 capa 0
     [[1,2,3],[4,5,6]],
    #Fila 1 y 2 capa 1
    [[7,8,9],[10,11,12]]
                    ])
print("ARRAY TRIDIMENSIONAL")
print(array_tri, "\n")
#===================================
#ARRAY CON RANGO
#===================================

array_rango = np.arange(0,10,2)
print("ARRAY CON RANGO")
print(array_rango, "\n")
#===================================
#OPERACIONES MATEMATICAS CON ARRAY UNIDIMENSIONAL
#===================================

#===================================
#SUMA
#===================================
array_sum_a = np.array([1,2,3,4,5])
array_sum_b = np.array([6,7,8,9,10])
array_res_sum = array_sum_a + array_sum_b
print("SUMA")
print("Array A   = ", array_sum_a)
print("Array B   = ", array_sum_b)
print("Resultado = ", array_res_sum,"\n")

#===================================
#RESTA
#===================================
array_res_a = np.array([12,14,16,18,20])
array_res_b = np.array([5,7,3,10,8])
array_res_resta = array_res_a - array_res_b
print("RESTA")
print("Array A   = ", array_res_a)
print("Array B   = ", array_res_b)
print("Resultado = ", array_res_resta,"\n")

#===================================
#MULTIPLICACION
#===================================
array_mul_a = np.array([1,2,3,4,5])
array_mul_b = np.array([6,7,8,9,10])
array_res_mul = array_mul_a * array_mul_b
print("MULTIPLICACION")
print("Array A   = ", array_mul_a)
print("Array B   = ", array_mul_b)
print("Resultado = ", array_res_mul,"\n")

#===================================
#DIVISION
#===================================
array_div_a = np.array([12,14,16,18,20])
array_div_b = np.array([2,2,2,2,2])
array_res_div = array_div_a / array_div_b
print("DIVISION")
print("Array A   = ", array_div_a)
print("Array B   = ", array_div_b)
print("Resultado = ", array_res_div,"\n")

#===================================
#SUMA BIDIMENSIONAL
#===================================
array_bid_sum_a = np.array([[1,3,5],[2,4,6]])
array_bid_sum_b = np.array([[6,7,8],[9,10,11]])
array_res_bid = array_bid_a + array_bid_b
print("SUMA BIDIMENSIONAL")
print("Array A   = ", array_bid_sum_a)
print("Array B   = ", array_bid_sum_b)
print("Resultado = ", array_res_bid,"\n")

#===================================
#RESTA BIDIMENSIONAL
#===================================
array_bid_res_a = np.array([[10,11,12],[13,14,15]])
array_bid_res_b = np.array([[6,7,8],[9,10,11]])
array_res_bid_res = array_bid_res_a - array_bid_res_b
print("RESTA BIDIMENSIONAL")
print("Array A   = ", array_bid_res_a)
print("Array B   = ", array_bid_res_b)
print("Resultado = ", array_res_bid_res,"\n")

#===================================
#Alfanumerico (en comillas simples)
#===================================

array_alf = np.array([["a","b","c"],["d","e","f"]])
print(array_alf)

array_a = np.array(["hola","mundo"])
print(np.char.upper(array_a))
print(np.char.lower(array_a))
print(np.char.add("prefijo_",array_a))

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matriz Original")
print(mat)

mat_rot_reloj = np.rot90(mat, k=-1)
print("\nMatriz rotada en sentido horario:")
print(mat_rot_reloj)

mat_rotada_anti_reloj = np.rot90(mat, k=1)
print("\nMatriz rotada en sentido antihorario:")
print(mat_rotada_anti_reloj)