# -*- coding: utf-8 -*-
"""DataONG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x4_wmMy6MMODjGmuOJS4tFtaMyZJDDEE

**IMPORTACIONES**
"""

import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt;
import seaborn as sns;

"""**CARGA DE DATOS**"""

data_frame = pd.read_csv("/content/1.6.3 DataONG.csv", low_memory=False)
data_frame.head()

"""cantidad de obsevaciones y la cantidad de características"""

data_frame.shape

"""**AVERIGUAR SI EXISTEN DATOS NULOS**"""

data_frame.isnull().any().any()

"""Conocer la cantidad de columnas categóricas y numéricas"""

# Agrupación de las columnas por tipo de datos
tipos = data_frame.columns.to_series().groupby(data_frame.dtypes).groups
# Conociendo la lista de columnas categóricas
ctext = tipos[np.dtype('object')]
len(ctext) # cantidad de columnas con datos categóricos.

# Conociendo la lista de columnas numéricas
columnas = data_frame.columns
cnum = list(set(columnas) - set(ctext))
len(cnum)

"""**TRATAMIENTO DE NULOS**"""

# Completando valores faltantes datos cuantititavos
for columna in cnum:
    mean = data_frame[columna].mean()
    data_frame[columna] = data_frame[columna].fillna(mean)

# Completando valores faltantes datos categóricos
for columna in ctext:
    mode = data_frame[columna].mode()[0]
    data_frame[columna] = data_frame[columna].fillna(mode)

# Se vuelve a comprobar los nulos
data_frame.isnull().any().any()

# Guardando el dataset preprocesado
# Save transform datasets
data_frame.to_csv("DataONG_procesado.csv", index=False)

# Calculando el porcentaje de donantes sobre toda la base de datos
porcent_donantes = (data_frame[data_frame.DONOR_AMOUNT > 0]['DONOR_AMOUNT'].count() * 1.0 / data_frame['DONOR_AMOUNT'].count()) * 100.0
print("El procentaje de donantes es {0:.2f}%"
.format(porcent_donantes))

"""**GRAFICO**"""

# Gráfico de tortas del porcentaje de donantes
# Agrupando por DONOR_FLAG
donantes = data_frame.groupby('DONOR_FLAG').IDX.count()
# Creando las leyendas del grafico.
labels = [ 'Donante\n' + str(round(x * 1.0 / donantes.sum() *
100.0, 2)) + '%' for x in donantes ]
labels[0] = 'No ' + labels[0]
plt.pie(donantes, labels=labels)
plt.title('Porcion de donantes')
plt.show()

"""**ANALISIS DEL GRAFICO**

Se ve que el porcentaje de personas que fueron donantes en el pasado es realmente muy bajo, solo
un 5.08% del total de personas (2423).
Este es un dato importante a tener en cuenta si se pretende, por ejemplo, clasificar; ya que al existir
tanta diferencia entre las clases a clasificar, esto puede afectar considerablemente al algoritmo de
aprendizaje.
Conviene ahora explorar con más detalle a este grupo pequeño de personas que fueron donantes;
veamos por ejemplo como se dividen de acuerdo a la cantidad de dinero donado.

**TRABAJANDO CON FILTRO**
"""

# Creando subset con solo los donates
data_donantes = data_frame[data_frame.DONOR_AMOUNT > 0]
data_donantes.shape

# Analizando el importe de donanciones
# Creando un segmentos de montos
monto_segm = pd.cut(data_donantes['DONOR_AMOUNT'], [0, 10, 20, 30, 40, 50, 60, 100, 200])

"""**GRAFICO**"""

# Creando el grafico de barras desde pandas
plot = pd.value_counts(monto_segm).plot(kind='bar', title='Montos de donación')
plot.set_ylabel('Nro. de donantes')
plot.set_xlabel('Rango de montos')
plt.show()

"""Es posible apreciar que la mayor cantidad de montos de donaciones se encuentra entre el rango 0
y 30
"""

# Agrupación por segmento según monto donado.
pd.value_counts(monto_segm)

"""**PREGUNTAS**

¿Cuál es el promedio de donaciones?
"""

# Monto de donación promedio
data_donantes['DONOR_AMOUNT'].mean()

# Gráfico de cajas del importe de donación
plt.boxplot(list(data_donantes['DONOR_AMOUNT']))
plt.title('Montos de donación')
plt.show()

"""**ANALIZANDO EL GRAFICO**

Este análisis muestra que la mayor cantidad de donaciones caen en un rango de importes entre 0 y
30 (tal y como se había eomentado antes), siendo la donación promedio 15.60. También es posible
ver que donaciones que superen un importe de 50 son casos realmente poco frecuentes, por lo que
constituyen valores atípicos y sería prudente eliminar estos casos al entrenar el modelo para que no
distorsionen los resultados.
Otra exploración interesante que se podría realizar sobre el set de datos relacionado con los donantes,
es ver cómo se divide este grupo en términos de género y edad.

¿Cuál es la distribución de los donantes por género?
"""

# Gráfico del género de los donantes
data_donantes.groupby('GENDER').size().plot(kind='bar')
plt.title('Distribución por género')
plt.show()

"""¿Cuál es la distribución de las donaciones según el género?"""

# Donaciones segùn el género
data_donantes[(data_donantes.DONOR_AMOUNT <= 50)
& (data_donantes.GENDER.isin(['F', 'M'])
)][['DONOR_AMOUNT', 'GENDER']].boxplot(by='GENDER')
plt.title('Donantes según género')
plt.show()

# Media de monto donado por mujeres
data_donantes[data_donantes.GENDER == 'F'][['DONOR_AMOUNT']].mean()

# Media de monto donado por hombres
data_donantes[data_donantes.GENDER == 'M'][['DONOR_AMOUNT']].mean()

"""Las mujeres suelen estar más propensas a donar, aunque donan un monto promedio menor (14.61)
al que donan los hombres (16.82).
Ahora se revisará el comportamiento de las donaciones respecto a la edad.

¿Cuál es la distribución de los donantes según edad?
"""

# Distribución de la edad de los donantes
data_donantes['AGE'].hist().set_title('Distribución de donantes según edad')
plt.show()

"""Para mejorar la visualización se genera el gráfico considerando rango de edades"""

# Agrupando la edad por rango de a 10
rango_edades = pd.cut(data_donantes['AGE'], range(0, 100, 10))
# Gráfico de barras de donaciones por edad
pd.value_counts(rango_edades).plot(kind='bar', title='Donaciones por rango de edad')
plt.show()

"""En este último análisis es posible apreciar que la mayor cantidad de los donantes son individuos
cuya edad se encuentra entre los 60 y 70 años, aunque la media de monto donado más alta la tienen
las personas que van desde los 30 a los 60 años.
"""